//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravFin
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinSostoyanie
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> SK { get; set; }
        public Nullable<int> VOA { get; set; }
        public Nullable<int> DKZ { get; set; }
        public Nullable<int> KKZ { get; set; }
        public Nullable<int> SZ { get; set; }
        public string FinanceSostoyanie { get; set; }
    }
}
