//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravFin
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalCabinet
    {
        public int Id { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Zametki { get; set; }
        public string DeloOne { get; set; }
        public string DeloTwo { get; set; }
        public string DeloThree { get; set; }
        public string DeloFour { get; set; }
        public string DeloFive { get; set; }
        public string DeloSix { get; set; }
    }
}
