//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravFin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Pol { get; set; }
        public Nullable<int> IDJobTittle { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string PassportData { get; set; }
        public string INN { get; set; }
        public string SNILS { get; set; }
        public string Photo { get; set; }
    
        public virtual JobTittles JobTittles { get; set; }
    }
}
