//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravFin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spravochnik
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public Nullable<int> IDJobTittle { get; set; }
        public Nullable<int> Nkabineta { get; set; }
        public string Telephone { get; set; }
    
        public virtual JobTittles JobTittles { get; set; }
    }
}
